In [1]:
import cv2
import numpy as np
cap = cv2.VideoCapture(0)
face_cascade = cv2.CascadeClassifier('sign_language-A-Classifier.xml')

In [2]:
while True:
    ret,photo = cap.read()
#    grey_image = cv2.cvtColor(photo,cv2.COLOR_BGR2HSV)
#    hands= hand_cascade.detectMultiScale(grey_image)
#    for(x,y,w,h) in hands:
#        cv2.rectangle(grey_image, (x,y), (x+w,y+h), (255,0,0), 5)
    myphoto=photo[5:250, 5:250]
    grey_image=cv2.cvtColor(photo,cv2.COLOR_BGR2GRAY)
    cv2.rectangle(photo,(5,5),(250,250),(255,0,0),5)
    hsv_image=cv2.cvtColor(photo,cv2.COLOR_BGR2HSV)
    hsv_image=cv2.cvtColor(myphoto,cv2.COLOR_BGR2HSV)
    lower_green=np.array([0,20,50])
    upper_green=np.array([20,250,250])
    mask=cv2.inRange(hsv_image, lower_green, upper_green)
    gesture = face_cascade.detectMultiScale(myphoto)
    print(gesture)
    if gesture is ():
        pass
        cv2.imshow('hi' , photo)
        if cv2.waitKey(1)==27:
            break
    else:
        for(x,y,w,h) in gesture:
            cv2.rectangle( photo , (x,y) , (x+w,y+h) , (255,0,0) , 5 )
            cv2.putText(photo, "It's A", (250, 450), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
            cv2.imshow('hi' , photo)
            cv2.imshow('hey',mask)
            if cv2.waitKey(1) == 27:
                break

#    cv2.rectangle(grey_image,(x,y),(x+w,y+h),(255,0,0),5)
#    cv2.rectangle(hsv_image,(x,y),(x+w,y+h),(255,0,0),5)
#    cv2.imshow('hi',photo)
#    cv2.imshow('hey',mask)
#    if cv2.waitKey(1)==27:
#        break
cv2.destroyAllWindows()
cap.release()

()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
[[ 56 116 125 125]]
[[ 54 107 132 132]]
[[ 56 108 122 122]]
[[ 55 101 126 126]]
[[ 52 100 123 123]]
[[ 50 100 119 119]]
[[ 31  86 137 137]]
[[ 38  94 124 124]]
[[ 34  96 124 124]]
()
[[ 30  92 128 128]]
[[ 27  81 145 145]]
[[ 24  86 137 137]]
()
[[ 21  93 128 128]]
[[ 24  95 121 121]]
[[ 26  99 112 112]]
()
()
[[ 23 103 113 113]]
[[ 24  99 120 120]]
[[ 22  98 125 125]]
()
[[ 28 105 112 112]]
[[ 26 105 116 116]]
[[ 27 100 122 122]]
[[ 25 105 122 122]]
[[ 24 105 118 118]]
[[ 27 108 110 110]]
[[ 25 111 108 108]]
()
[[ 24 101 119 119]]
[[ 23 106 113 113]]
[[ 22 102 118 118]]
[[ 19  96 126 126]]
[[ 24 102 116 116]]
[[ 21  98 125 125]]
[[ 19  98 124 124]]
[[ 18  92 132 132]]
[[ 19  96 122 122]]
[[ 22 101 116 116]]
[[ 18  93 129 129]]
[[ 21 102 118 118]]
[[ 19  99 121 121]]
[[ 19  99 122 122]]
[[ 17  91 129 129]]
[[ 20  96 121 121]]


()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
[[ 61  39 121 121]]
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()

In [ ]:
cap.release()


In [ ]:
gesture = face_cascade.detectMultiScale(myphoto)
print(gesture)
if gesture is ():
     pass
else:
        for(x,y,w,h) in gesture:
            cv2.rectangle( photo , (x,y) , (x+w,y+h) , (255,0,0) , 5 )
            cv2.putText(photo, "It's A", (250, 450), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
            cv2.imshow('hi' , photo)
            if cv2.waitKey(1) == 27:
                break
